# Generated by Django 3.0 on 2020-09-21 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sure_name', models.CharField(max_length=100)),
                ('telephon', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck.department')),
            ],
        ),
        migrations.CreateModel(
            name='header_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promised_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck.employee')),
            ],
        ),
        migrations.CreateModel(
            name='truck_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100)),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck.truck_type')),
            ],
        ),
        migrations.CreateModel(
            name='list_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('destination', models.CharField(max_length=100)),
                ('delivery_date', models.DateField()),
                ('remake', models.CharField(max_length=200)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck.delivery_note')),
                ('header_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck.header_report')),
            ],
        ),
        migrations.AddField(
            model_name='header_report',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck.truck'),
        ),
    ]
